#
# adding ringtable
#
UP:
  create_table:
    ringsites:
      link_id:
        type: integer
        length: 10
        not_null:
      hits:
        type: integer
        length: 10
        default: 0
      position:
        type: integer
        length: 10
        default: 0
      url:
        type: string
        length: 255
        default: null
        is_null:
      email:
        type: string
        length: 128
        is_null:
        default: null
      status:
        type: integer
        length: 4
        not_null:
        default: 1
DOWN:
  drop_table: ringsites